let products=[],cart=[],active='All';
const money=n=>'GYD $'+Number(n||0).toLocaleString();
async function load(){const r=await fetch('/api/products');products=await r.json();renderProducts();}
function renderProducts(){let q=(document.getElementById('search')?.value||'').toLowerCase();let list=products.filter(p=>(active==='All'||p.cat===active)&&(!q||p.name.toLowerCase().includes(q)));document.getElementById('grid').innerHTML=list.map(p=>`<article class="card"><img src="${p.img}"><span class="cat">${p.cat}</span><h3>${p.name}</h3><div class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><div class="stock">${p.stock>0?'In stock':'Out of stock'}</div><button class="add" ${p.stock<1?'disabled':''} onclick="add(${p.id})">🛒 Add to Cart</button></article>`).join('')||'<p>No products found.</p>'}
function filterCat(c){active=c;renderProducts();document.getElementById('products').scrollIntoView({behavior:'smooth'})}
function add(id){let p=products.find(x=>x.id===id);if(!p||p.stock<1)return;let x=cart.find(x=>x.id===id);x?x.qty=Math.min(x.qty+1,p.stock):cart.push({...p,qty:1});updateCart();openCart()}
function updateCart(){document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);document.getElementById('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartrow"><img src="${x.img}"><div><b>${x.name}</b><br>${money(x.price)} × ${x.qty}</div><button onclick="removeItem(${x.id})">×</button></div>`).join(''):'<p>Your cart is empty.</p>';document.getElementById('cartTotal').textContent=money(cart.reduce((s,x)=>s+x.price*x.qty,0))}
function removeItem(id){cart=cart.filter(x=>x.id!==id);updateCart()}
function openCart(){document.getElementById('drawer').classList.add('open');updateCart()}function closeCart(){document.getElementById('drawer').classList.remove('open')}
async function placeOrder(){if(!cart.length)return alert('Your cart is empty.');let customer={name:document.getElementById('name').value.trim(),phone:document.getElementById('phone').value.trim(),address:document.getElementById('address').value.trim()};let payment=document.getElementById('payment').value;if(!customer.name||!customer.phone||!customer.address)return alert('Please enter your name, phone and delivery address.');let total=cart.reduce((s,x)=>s+x.price*x.qty,0);let r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,payment,items:cart.map(x=>({id:x.id,name:x.name,qty:x.qty,price:x.price})),total})});let data=await r.json();if(!r.ok)return alert(data.error||'Unable to place order');let msg=`Meridian Trading Order ${data.order.id}%0AName: ${customer.name}%0APhone: ${customer.phone}%0AAddress: ${customer.address}%0APayment: ${payment}%0AItems:%0A${cart.map(x=>`${x.name} x${x.qty} - ${money(x.price*x.qty)}`).join('%0A')}%0ATotal: ${money(total)}`;cart=[];updateCart();window.open('https://wa.me/5926999929?text='+msg,'_blank');alert('Order '+data.order.id+' created. WhatsApp will open to confirm the order.');}
load();
